### ISSUE TITLE
Adapt uruk to clojure.data.xml 0.1.0-beta2

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#10]
Hi Dave,

we'll need namespace support rather sooner than later, can you have a look at making uruk use `[org.clojure/data.xml "0.1.0-beta1"]`?

Thanks!
Hans

**Comment by daveliepmann** [comment]
Version 0.3.1, now on Clojars, relies on clojure.data.xml 0.1.0-beta1. I have a few tests touching on Elements but I'll wait to close this until you report it works for your purposes.

**Comment by hanshuebner** [comment]
Dang, sorry!  I posted this request in the morning, before I got into using the new clojure.data.xml myself.  I found that the current version is beta2, so can you make another release depending on that?  I'll then try it out to see whether it works for the application that I'm working on.  Thanks!

**Comment by daveliepmann** [comment]
No problem. Clojars now has 0.3.2, which depends on beta2.

**Comment by hanshuebner** [comment]
Thanks!  I'll let you know if there are any issues.

-Hans

**Comment by daveliepmann** [comment]
👍

**Comment by hanshuebner** [comment]
I think this works for now.  We'll open new issues if needed.

**Comment by daveliepmann** [comment]
Excellent, glad to hear it. Thanks!
