### ISSUE TITLE
clojure.edn is called without being required

### ISSUE THREAD

**Issue by yenda** [daveliepmann/uruk#13]
[code](https://github.com/daveliepmann/uruk/blob/d720bd76d91e4bbd8844e16b9b64af150f099c5c/src/uruk/core.clj#L79)

I think this is what causes a project to fail if clojure.edn has not been required yet when uruk itself is being required.

> Exception in thread "main" java.lang.ExceptionInInitializerError
>     at clojure.main.<clinit>(main.java:20)
> Caused by: java.lang.ClassNotFoundException: clojure.edn, compiling:(uruk/core.clj:79:7)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyze(Compiler.java:6625)
>     at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyze(Compiler.java:6625)
>     at clojure.lang.Compiler$IfExpr$Parser.parse(Compiler.java:2797)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyze(Compiler.java:6625)
>     at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
>     at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6319)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyze(Compiler.java:6625)
>     at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
>     at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
>     at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6856)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.access$300(Compiler.java:38)
>     at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:589)
>     at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
>     at clojure.lang.Compiler.analyze(Compiler.java:6669)
>     at clojure.lang.Compiler.analyze(Compiler.java:6625)
>     at clojure.lang.Compiler.eval(Compiler.java:6931)
>     at clojure.lang.Compiler.load(Compiler.java:7379)

**Comment by daveliepmann** [comment]
Investigating now

**Comment by daveliepmann** [comment]
I'm not immediately able to replicate this error but I recognize the symptoms.

**Comment by daveliepmann** [comment]
Try [0.3.4](https://clojars.org/uruk/versions/0.3.4)

**Comment by daveliepmann** [comment]
Please reopen if it does not help

**Comment by daveliepmann** [comment]
Could you post a dependencies tree to help me replicate the issue?

**Comment by yenda** [comment]
It's fixed.Thanks
