### ISSUE TITLE
Options as "&rest" arguments

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#2]
I notice that you're using `& {:keys [options variables types]}` in some function signatures.  Can you change those so that options are passed as map instead (`{:keys [options variables types]}`).  Doing it that way makes it easier to compose functions.

**Comment by daveliepmann** [comment]
Like so?

`[session module & {:keys [options variables types]}]`
to
`[session module & [{:keys [options variables types]}]]`
?

**Comment by hanshuebner** [comment]
The usual idiom would be

```
(defn foo
  ([session module] (foo session module {}))
  ([session module {:keys [options variables types]}] ...))
```

Your solution should work as well, but it seems a bit less conventional.
