### ISSUE TITLE
execute-xquery and variables

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#3]
It seems that the variables argument to execute-xquery is not actually used down in the code.  This is something that I actually need before I can really start using the library.

**Comment by daveliepmann** [comment]
I borked the reference to this thread in the commit message, but 05fef19d7961eac598733d9d83a7d01b748bbb30 should fix this.

**Comment by daveliepmann** [comment]
I'm considering the best way to allow passing of non-string variables, as well.

**Comment by hanshuebner** [comment]
Your fix works, and the limitation to string variables immediately crept up as a problem :)  - One way to deal with it would be to look at the query to determine the types of the external variables, but that may require some infrastructure to avoid repeatedly parsing of the query.

**Comment by daveliepmann** [comment]
I'm wary of getting into the business of parsing Xquery directly. Do you have an example of such a query?

In the meantime, I am writing an approach that requires declaration of variable type in the variable map. I'm leaning towards each value being a map, e.g.:

`{"my-variable-name" {:value "my-variable-value" ;; mandatory
                                       ;; optional:
                                       :namespace "my-namespace"
                                       :type :attribute}`

...which would default to `:namespace nil, :type :xs-string`. Values that aren't maps would default similarly.

**Comment by hanshuebner** [comment]
I like your approach, and it should not conflict with a more automatic solution.

The idea would not be to parse the query - I'd rather hope that MarkLogic has some functionality with which you could ask it to parse an XQuery and return information about the parsed query.  I'm not sure if such a function exists, but I can ask on the mailing list.

**Comment by daveliepmann** [comment]
Version 0.2.3 adds support for non-XS_STRING variables using maps as I proposed above. Documentation is in the README.

I'm going to close this for now, with the understanding that we are still keeping the possibility open of automatic query parsing to get variable types as Hans describes.
