### ISSUE TITLE
Is uruk converting single-element result sequences into the single element?

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#6]
I observe that if a query returns only one result, `execute-xquery` returns the single element, whereas if multiple results are matched, a sequence is returned.  Is this done by XCC or by uruk?  It would be nice if the caller of `execute-xquery` could specify whether one or multiple results are returned.  If one result is expected but the query returns more than one, an error should by signaled.

**Comment by daveliepmann** [comment]
This is done by uruk. I'll see about specifying results as you describe.

**Comment by daveliepmann** [comment]
[Common Lisp model](http://marijnhaverbeke.nl/postmodern/postmodern.html#querying)

**Comment by daveliepmann** [comment]
Please see 0.2.4 for a solution using [`shape-results`](https://github.com/daveliepmann/uruk/blob/master/src/uruk/core.clj#L260). I'm not sure this is how I'd like this issue to be solved long-term but it answers the problem for now. Feedback welcome.

See examples of [:single](https://github.com/daveliepmann/uruk/blob/master/src/uruk/examples/types.clj#L189) and [:single!](https://github.com/daveliepmann/uruk/blob/master/src/uruk/examples/types.clj#L179).
