### ISSUE TITLE
Support XML element argument type

### ISSUE THREAD

**Issue by hanshuebner** [daveliepmann/uruk#9]
It should be possible to pass an XML element as argument to an XQuery invocation.  The given argument should be efficiently converted so that it is possible to either pass hiccup-style s-expression encoded elements or clojure.data.xml.Element instances.

**Comment by daveliepmann** [comment]
Version 0.2.6, now available, handles `document-node` and `element` variables given as a String, hiccup-style vector, or clojure.data.xml.Element.

**Comment by hanshuebner** [comment]
I had intended to request that XML elements passed as arguments from Clojure would be arriving in the Query as `element`, not `xs:string`.  I know that it is possible to parse the string to an XML element in the query, and it may actually be faster, yet I find that to be an extra step it would also look better if XML arguments could be declared as having the type `element()`.  Can you investigate whether that'd be easy to implement and discuss if in doubt?

**Comment by daveliepmann** [comment]
We're currently using [Request.setNewVariable](https://docs.marklogic.com/javadoc/xcc/com/marklogic/xcc/Request.html#setNewVariable%28java.lang.String,%20com.marklogic.xcc.types.ValueType,%20java.lang.Object%29) with ValueType set to  `element()`, which from my research appears to be the extent that a variable passed in can be declared to be `element()`. As you say, it appears to still be necessary to `xdmp:unquote` or otherwise parse such a variable.

I will investigate further.

**Comment by daveliepmann** [comment]
See http://developer.marklogic.com/pipermail/general/2016-July/019265.html

**Comment by daveliepmann** [comment]
At this point I'm confident that Uruk is doing everything in its power to send XML elements through as elements. The variable type is set on the MarkLogic side, and in XQuery the `node-kind` is coming through as "element" without any casting:

```
(with-open [session (create-session db)]
  (execute-xquery session "xquery version \"1.0-ml\";
                           declare variable $my-variable external;
                           xdmp:node-kind($my-variable)"
                  {:variables {"my-variable" {:value "<foo/>"
                                              :type :element}}
                   :shape :single!}))
=> "element"
```

...therefore I am closing this for the moment. If other scenarios with XML element type issues arise, we can reopen.
